# --- Paths
export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.cargo/bin:$PATH"

# --- Run at startup
tmux

# ---  Set theme
ZSH_THEME="dallas"

# --- Add plugins. Too many will slowdown startup.
plugins=(git hitchhiker)

# --- Set case sensitive completion
# CASE_SENSITIVE="true"

# --- Set hyphen-insensitive completion. Only works if case sensitive is off.
HYPHEN_INSENSITIVE="true"

# --- Change the auto-update behavior and frequency (days)
zstyle ':omz:update' mode auto  # other options are -> auto / reminder
zstyle ':omz:update' frequency 26

# --- Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# --- Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# --- Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# --- Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# --- Display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts in zsh
COMPLETION_WAITING_DOTS="true"

# --- Uncomment to disable marking untracked files under VCS as dirty.
# --- This makes repository status check for large repositories much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# --- Change the command execution timestamp shown in the history.
# --- Three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# --- Manually set your language environment
export LANG=en_US.UTF-8

# --- PERSONAL ALIASES --- #
alias ccw='cc -Wall -Wextra -Werror'
alias hit='hitchhiker'
alias neo='neofetch'
alias norm='norminette -R CheckForbiddenSourceHeader'
alias vim='nvim'

# --- Source OMZ! and custom plugins
source $ZSH/oh-my-zsh.sh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
