# Run at start up
tmux
#!_________________________
# Paths
export PATH="$HOME/.cargo/bin:$PATH"
#!-------------------------
# Aliases
alias neo='neofetch'
alias vim='nvim'
alias ccw='cc -Wall -Wextra -Werror'
alias norm='norminette -R CheckForbiddenSourceHeader'
